name: nginx-deploy

releases: 
- name: nginx-release
  version: latest

update:
 canaries: 1
 max_in_flight: 1
 canary_watch_time: 1000-60000
 update_watch_time: 1000-60000

stemcells:
- alias: ubuntu
  os: ubuntu-xenial
  version: latest

instance_groups:
- name: nginx
  azs: [z1]
  instances: 1
  jobs:
  - name: nginx
    release: nginx-release
  vm_type: default
  networks:
  - name: default
  stemcell: ubuntu 
